apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
data:
  # NOTE: https://github.com/helm/helm/issues/2798#issuecomment-470435015
  kwok-config.yaml: |-
    apiVersion: config.kwok.x-k8s.io/v1alpha1
    kind: KwokConfiguration
    options:
      enableProfilingHandler: false
      enableContentionProfiling: false
      enablePodsOnNodeSyncListPager: false
      enablePodsOnNodeSyncStreamWatch: true
      nodeLeaseParallelism: 4
      podPlayStageParallelism: 4
      nodePlayStageParallelism: 4
      enableCRDs:
      - Stage