apiVersion: flowcontrol.apiserver.k8s.io/v1beta3
kind: FlowSchema
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: {{ .Values.flowcontrol.matchingPrecedence }}
  priorityLevelConfiguration:
    name: {{ .Values.flowcontrol.priorityLevelConfiguration }}
  rules:
  - resourceRules:
    - apiGroups:
      - '*'
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    subjects:
    - kind: ServiceAccount
      serviceAccount:
        name: {{ .Values.name }}
        namespace: {{ .Release.Namespace }}
