apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}-init-spec
  namespace: {{ .Release.Namespace }}
data:
  spec: {{ .Values.runnerGroupSpec | b64dec | toYaml | indent 2 }}
