count: 10
loadProfile:
  version: 1
  description: "list configmaps"
  spec:
    rate: 10
    conns: 10
    client: 10
    contentType: json
    disableHTTP2: false
    maxRetries: 0
    requests:
      - staleList:
          version: v1
          resource: configmaps
        shares: 100 # chance 100 / (100 + 100)
      - quorumList:
          version: v1
          resource: configmaps
        shares: 100 # chance 100 / (100 + 100)
