# SLI Read-Only Node10 Job1 Pod1k load profile
count: 10
loadProfile:
  version: 1
  description: "10nodes_1000pods"
  spec:
    rate: 10
    conns: 10
    client: 10
    contentType: json
    requests:
    - staleList:
        version: v1
        resource: pods
        namespace: job1pod1k
      shares: 10
    - staleGet:
        version: v1
        resource: pods
        namespace: virtualnodes-kperf-io
        name: node10job1pod1k-1
      shares: 300
    - staleList:
        version: v1
        resource: nodes
        namespace: virtualnodes-kperf-io
      shares: 10
    - staleList: # cluster scoped
        version: v1
        resource: nodes
      shares: 10
    - staleList: # cluster scoped
        version: v1
        resource: namespace
      shares: 10
    - staleList:
        version: v1
        resource: jobs
        namespace: job1pod1k
      shares: 10
    - staleGet:
        version: v1
        resource: jobs
        namespace: job1pod1k
        name: batchjobs
      shares: 300
