# SLI Read-Only Node100 Job10 Pod10k load profile
count: 10
loadProfile:
  version: 1
  description: "100nodes_10job_1000pods"
  spec:
    rate: 10
    conns: 10
    client: 10
    contentType: json
    requests:
    - staleList:
        version: v1
        resource: pods
        namespace: job10pod10k
      shares: 10
    - staleGet:
        version: v1
        resource: pods
        namespace: virtualnodes-kperf-io
        name: node100job10pod10k-1
      shares: 300
    - staleList:
        group: batch
        version: v1
        resource: jobs
        namespace: job10pod10k
      shares: 10
    - staleGet:
        group: batch
        version: v1
        resource: jobs
        namespace: job10pod10k
        name: batchjobs
      shares: 300
    - staleList: # cluster scope
        version: v1
        resource: nodes
      shares: 10
    - staleList: #cluster scope
        version: v1
        resource: namespaces
      shares: 10
    - staleGet: # cluster scope
        version: v1
        resource: nodes
        name: node100job10pod10k-3
      shares: 300
    - staleGet: # cluster scope
        version: v1
        resource: namespaces
        name: job10pod10k
      shares: 300
