version: 1
description: "test=mutation"
spec:
  rate: 10
  total: 1
  conns: 10
  client: 10
  contentType: json
  disableHTTP2: false
  maxRetries: 0
  requests:
    - delete:
        version: v1
        resource: pods
        namespace: kperf
        name: mutate2
      shares: 1000 # chance 1000 / (1000 + 100 + 100)
