name: CI
on:
  pull_request:
    branches: ['main']
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --config .golangci.yml --timeout=8m

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: test
        run: make test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: build
        run: make build
      - name: image-build
        run: make image-build
